name: CitybuildSystem
version: 1.0.0
main: de.flunar.citybuildsystem.CitybuildSystem
api-version: '1.20'

commands:
  spawn:
    description: Teleportiert dich zum gesetzten Spawnpunkt.
    usage: /spawn
  tpsmonitor:
    description: Toggles the TPS monitor.
    usage: /tpsmonitor
  setspawn:
    description: Sets the spawn point.
    usage: /setspawn
    permission: flunar.admin