name: CitybuildSystem
version: 1.0.0
main: de.flunar.citybuildsystem.CitybuildSystem
api-version: '1.20'

commands:
  setspawn:
    description: Setzt den Spawnpunkt für die Spieler.
    usage: /setspawn
  spawn:
    description: Teleportiert dich zum gesetzten Spawnpunkt.
    usage: /spawn
