name: CitybuildSystem
version: 1.0.0
main: de.flunar.citybuildsystem.CitybuildSystem
api-version: '1.20'

commands:
  spawn:
    description: Teleportiert den Spieler zur Spawn-Location mit der ID 1.
    usage: /spawn
  farmwelt:
    description: Teleportiert den Spieler zur Spawn-Location mit der ID 1.
    usage: /farmwelt
  setspawn:
    description: Sets the spawn point.
    usage: /setspawn
    permission: flunar.admin
  cbhelp:
    description: Help Command
    usage: /cbhel
  cbgui:
    description: Öffnet das Citybuild GUI.
  nether:
    description: Teleport to a random safe location in the Nether.
  end:
    description: Teleport to a random safe location in the End.
  grundstück:
    description: Open the Grundstück GUI.
    aliases: [ gs ]