name: CitybuildSystem
version: 1.0.0
main: de.flunar.citybuildsystem.CitybuildSystem
api-version: '1.20'

commands:
  spawn:
    description: Teleportiert den Spieler zur Spawn-Location mit der ID 1.
    usage: /spawn
  farmwelt:
    description: Teleportiert den Spieler zur Spawn-Location mit der ID 1.
    usage: /farmwelt
  setspawn:
    description: Sets the spawn point.
    usage: /setspawn
    permission: flunar.admin
  cbhelp:
    description: Help Command
    usage: /cbhel
  hide:
    description: Macht einen Spieler unsichtbar für andere Spieler.
    usage: /hide
  cbgui:
    description: Öffnet das Citybuild GUI.